test

diff --git a/.github/workflows/ollama-review.yaml b/.github/workflows/ollama-review.yaml
--- a/.github/workflows/ollama-review.yaml
+++ b/.github/workflows/ollama-review.yaml
@@ -26,16 +26,29 @@ jobs:
         id: changed-files
         uses: tj-actions/changed-files@v43
 
-      - name: Review code
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Get git diff
+        id: git_diff
         run: |
-          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
-            gh pr comment ${{ github.event.pull_request.number }} --body "$(cat $file)"
-            review=$(curl -s http://127.0.0.1:11434/api/generate -d '{"model": "codellama", "prompt": "You are an expert programmer in golang that writes simple, concise code and explanations.Review the following file:\n\n```\n$(cat $file)\n```", "stream": false}' | jq -r '.response')
-            comment="Ollama Code Review for \`$file\`:\n\n$review"
-            echo "$comment" >> ollama_review.txt
-          done
+          git fetch origin
+          git diff origin/main... > diff.txt
+          echo "::set-output name=diff::$(cat diff.txt)"
+
+      - name: Run Ollama Review
+        run: |
+          diff_content=$(cat diff.txt | jq -sRr @json)
+
+          json_payload=$(jq -n \
+            --arg model codellama \
+            --arg prompt "You are an expert programmer in golang that writes simple, concise code and explanations. Review the following Git diff and provide your feedback:\n\n\`\`\`diff\n$diff_content\n\`\`\`" \
+            '{model: $model, prompt: $prompt, stream: false}')
+
+          response=$(curl -s --max-time 30 --retry 3 --retry-delay 5 -X POST http://127.0.0.1:11434/api/generate -d "$json_payload")
+          if [ $? -ne 0 ]; then
+            echo "Request to Ollama API failed" >> ollama_review.txt
+          else
+            review=$(echo "$response" | jq -r '.response')
+            echo "Ollama Code Review:\n\n$review" > ollama_review.txt
+          fi
           
           gh pr comment ${{ github.event.pull_request.number }} --body "$(cat ollama_review.txt)"
-        shell: bash
+
